apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - crd/bases/webaudio.example.com_providerconfigs.yaml
  - crd/bases/webaudio.example.com_sequencers.yaml
  - crd/bases/webaudio.example.com_steps.yaml
  - crd/bases/webaudio.example.com_tracks.yaml
  - deploy/namespace.yaml
  - deploy/serviceaccount.yaml
  - deploy/clusterrole.yaml
  - deploy/clusterrolebinding.yaml
  - deploy/deployment.yaml
  - deploy/service.yaml
  - deploy/ingress.yaml
